### PR TITLE
v3.9.8

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by nehaljwani** [comment]
Supersedes https://github.com/conda-forge/pycryptodome-feedstock/pull/23

**Comment by nehaljwani** [comment]
cc @CJ-Wright

**Comment by CJ-Wright** [comment]
Thank you!

**Comment by nehaljwani** [comment]
I don't have merge rights. Could you hit the merge button?

**Comment by CJ-Wright** [comment]
Let me give the maintainers some time. @conda-forge/pycryptodome 

On a related note, do you want to be a maintainer?

**Comment by nehaljwani** [comment]
I am already maintaining https://github.com/conda-forge/pycryptodomex-feedstock ... I guess I can maintain this one too.

**Pull request merged**
